bookie_enabled:
  client: true
  default: true
  type: bool

bookie_starting_balance:
  default: 1000
  type: integer

bookie_weekly_bonus:
  default: 100
  type: integer

bookie_min_bet:
  default: 10
  type: integer

bookie_currency_name:
  default: "coins"
  client: true
  type: string

bookie_achievements_started_at:
  default: "2026-05-02T07:30:00Z"
  type: string

bookie_acca_max_legs:
  default: 8
  type: integer

bookie_acca_league_points:
  default: 5
  type: integer

bookie_acca_league_min_odds:
  default: 4.0
  type: float

bookie_max_open_accas:
  default: 3
  type: integer

bookie_new_achievements_started_at:
  default: "2026-06-06T00:00:00Z"
  type: string
